QA-7641 updated all workflows and submit history locator

diff --git a/.github/workflows/bha-tests.yml b/.github/workflows/bha-tests.yml
--- a/.github/workflows/bha-tests.yml
+++ b/.github/workflows/bha-tests.yml
@@ -42,6 +42,11 @@ jobs:
         if: ${{ github.event_name != 'repository_dispatch' }}
         run: |
           echo "::set-output name=matrix::{\"environment\": [\"production\", \"staging\"]}"
+      - id: invalid-deploy
+        if: ${{ github.event_name == 'repository_dispatch' && github.event.client_payload.environment != 'production' }}
+        run: |
+          echo "Invalid environment: ${{ github.event.client_payload.environment }}"
+          exit 1
 
 
   build:
