QA-8094 PR for FindByID testplan

diff --git a/.github/workflows/casesearch-split-screen-tests.yml b/.github/workflows/casesearch-split-screen-tests.yml
--- a/.github/workflows/casesearch-split-screen-tests.yml
+++ b/.github/workflows/casesearch-split-screen-tests.yml
@@ -20,7 +20,23 @@ on:
     - cron: '0 8 * * 1-5'
 
 jobs:
+  block_invalid_env:
+    runs-on: ubuntu-latest
+    steps:
+      - id: invalid-deploy
+        if: ${{ github.event_name == 'repository_dispatch' && github.event.client_payload.environment != 'production' }}
+        run: |
+          echo "❌ Deployment runs are not meant for the 'non-production' environment."
+          exit 1
+
+      - id: block-non-approved
+        if: ${{ github.event_name == 'repository_dispatch' && github.event.client_payload.environment == 'india' }}
+        run: |
+          echo "❌ Invalid environment: ${{ github.event.client_payload.environment }}"
+          exit 1
+
   set_matrix:
+    needs: block_invalid_env
     runs-on: ubuntu-latest
     if: ${{ !(github.event_name == 'repository_dispatch' && github.event.client_payload.environment == 'staging') }}
     outputs:
@@ -42,16 +58,6 @@ jobs:
         if: ${{ github.event_name != 'repository_dispatch' }}
         run: |
           echo "::set-output name=matrix::{\"environment\": [\"production\", \"staging\"]}"
-      - id: invalid-deploy
-        if: ${{ github.event_name == 'repository_dispatch' && github.event.client_payload.environment != 'production' }}
-        run: |
-          echo "Invalid environment: ${{ github.event.client_payload.environment }}"
-          exit 1
-      - id: block-india-deploy
-        if: ${{ github.event_name == 'repository_dispatch' && github.event.client_payload.environment == 'india' }}
-        run: |
-          echo "India environment is not allowed for deployment runs."
-          exit 1
 
   build:
     needs: set_matrix
@@ -209,7 +215,7 @@ jobs:
             } else if (CC_EVENT != 'repository_dispatch' && CC_ENV == 'india' && JOB_STATUS == 'failure') {
               SLACK_WEBHOOK_URL = '${{ secrets.SLACK_WEBHOOK_URL_USH }}';
               SLACK_CHANNEL_ID = '${{ secrets.SLACK_CHANNEL_ID_USH }}';
-              console.log("India Success");
+              console.log("India Failure");
             } else {
               SLACK_WEBHOOK_URL = '';
               SLACK_CHANNEL_ID = '';
