QA-8032 more changes for slack notification 1

diff --git a/.github/workflows/hq-smoke-tests.yml b/.github/workflows/hq-smoke-tests.yml
--- a/.github/workflows/hq-smoke-tests.yml
+++ b/.github/workflows/hq-smoke-tests.yml
@@ -263,29 +263,171 @@ jobs:
         run: |
           echo "COMBINED_JSON=$COMBINED_JSON"
           echo "COMBINED_URL=$COMBINED_URL"
+#
+#      - name: Post to Slack channel on Success
+#        if: ${{ fromJSON(steps.configure_slack.outputs.result).SLACK_WEBHOOK_URL != '' && success() }}
+#        uses: slackapi/slack-github-action@v1.23.0
+#        with:
+#          payload: |
+#            {
+#              "attachments": [
+#                {
+#                  "color": "#36a64f",
+#                  "blocks": [
+#                    {
+#                      "type": "section",
+#                      "text": {
+#                        "type": "mrkdwn",
+#                        "text": "Hey 👋 \n*${{ github.workflow }}* just finished successfully! 🎉\n"
+#                      }
+#                    },
+#                    {
+#                      "type": "section",
+#                      "text": {
+#                        "type": "mrkdwn",
+#                        "text": "*Passed:* ${{ steps.parse_counts.outputs.PASSED }}  *Failed:* ${{ steps.parse_counts.outputs.FAILED }}  *Error:* ${{ steps.parse_counts.outputs.ERROR }}  *Skipped:* ${{ steps.parse_counts.outputs.SKIPPED }}  *XFail:* ${{ steps.parse_counts.outputs.XFAIL }}"
+#                      }
+#                    },
+#                    {
+#                      "type": "context",
+#                      "elements": [
+#                        {
+#                          "type": "mrkdwn",
+#                          "text": "*Environment:* ${{ matrix.environment }}"
+#                        },
+#                        {
+#                          "type": "mrkdwn",
+#                          "text": "*Status:* ✅ Passed"
+#                        }
+#                      ]
+#                    },
+#                    {
+#                      "type": "image",
+#                      "title": {
+#                        "type": "plain_text",
+#                        "text": "Test Summary Charts"
+#                      },
+#                      "image_url": "${{ env.COMBINED_URL }}",
+#                      "alt_text": "Pie + Bar Chart"
+#                    },
+#                    {
+#                      "type": "section",
+#                      "text": {
+#                        "type": "mrkdwn",
+#                        "text": "Here's the corresponding report :arrow_right::arrow_right:"
+#                      },
+#                      "accessory": {
+#                        "type": "button",
+#                        "text": {
+#                          "type": "plain_text",
+#                          "text": "Click to Download",
+#                          "emoji": true
+#                        },
+#                        "url": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}/artifacts/${{ steps.artifact-upload-step.outputs.artifact-id }}",
+#                        "style": "primary",
+#                        "action_id": "button-action"
+#                      }
+#                    }
+#                  ]
+#                }
+#              ]
+#            }
+#
+#        env:
+#          SLACK_WEBHOOK_URL: ${{ fromJSON(steps.configure_slack.outputs.result).SLACK_WEBHOOK_URL }}
+#          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
+#
+#      - name: Post to Slack channel on Failure
+#        if: ${{ fromJSON(steps.configure_slack.outputs.result).SLACK_WEBHOOK_URL != '' && failure() }}
+#        uses: slackapi/slack-github-action@v1.23.0
+#        with:
+#          payload: |
+#            {
+#              "attachments": [
+#                {
+#                  "color": "#FF0000",
+#                  "blocks": [
+#                    {
+#                      "type": "section",
+#                      "text": {
+#                        "type": "mrkdwn",
+#                        "text": "Hey 👋 \n*${{ github.workflow }}* has failed! ❌\n"
+#                      }
+#                    },
+#                    {
+#                      "type": "section",
+#                      "text": {
+#                        "type": "mrkdwn",
+#                        "text": "*Passed:* ${{ steps.parse_counts.outputs.PASSED }}  *Failed:* ${{ steps.parse_counts.outputs.FAILED }}  *Error:* ${{ steps.parse_counts.outputs.ERROR }}  *Skipped:* ${{ steps.parse_counts.outputs.SKIPPED }}  *XFail:* ${{ steps.parse_counts.outputs.XFAIL }}"
+#                      }
+#                    },
+#                    {
+#                      "type": "context",
+#                      "elements": [
+#                        {
+#                          "type": "mrkdwn",
+#                          "text": "*Environment:* ${{ matrix.environment }}"
+#                        },
+#                        {
+#                          "type": "mrkdwn",
+#                          "text": "*Status:* ❌ Failed"
+#                        }
+#                      ]
+#                    },
+#                    {
+#                      "type": "image",
+#                      "title": {
+#                        "type": "plain_text",
+#                        "text": "Test Summary Charts"
+#                      },
+#                      "image_url": "${{ env.COMBINED_URL }}",
+#                      "alt_text": "Pie + Bar Chart"
+#                    },
+#                    {
+#                      "type": "section",
+#                      "text": {
+#                        "type": "mrkdwn",
+#                        "text": "Here's the corresponding report :arrow_right::arrow_right:"
+#                      },
+#                      "accessory": {
+#                        "type": "button",
+#                        "text": {
+#                          "type": "plain_text",
+#                          "text": "Click to Download",
+#                          "emoji": true
+#                        },
+#                        "url": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}/artifacts/${{ steps.artifact-upload-step.outputs.artifact-id }}",
+#                        "style": "danger",
+#                        "action_id": "button-action"
+#                      }
+#                    }
+#                  ]
+#                }
+#              ]
+#            }
 
-      - name: Post to Slack channel on Success
-        if: ${{ fromJSON(steps.configure_slack.outputs.result).SLACK_WEBHOOK_URL != '' && success() }}
-        uses: slackapi/slack-github-action@v1.23.0
+      - name: Post Slack Notification
+        if: ${{ success() || failure() }}
+        uses: slackapi/slack-github-action@v1.25.0
         with:
           payload: |
             {
               "attachments": [
                 {
-                  "color": "#36a64f",
+                  "color": "${{ job.status == 'success' && '#36a64f' || '#FF0000' }}",
                   "blocks": [
                     {
                       "type": "section",
                       "text": {
                         "type": "mrkdwn",
-                        "text": "Hey 👋 \n*${{ github.workflow }}* just finished successfully! 🎉\n"
+                        "text": "Hola 👋 \n*${{ github.workflow }}* just ran!"
                       }
                     },
                     {
                       "type": "section",
                       "text": {
                         "type": "mrkdwn",
-                        "text": "*Passed:* ${{ steps.parse_counts.outputs.PASSED }}  *Failed:* ${{ steps.parse_counts.outputs.FAILED }}  *Error:* ${{ steps.parse_counts.outputs.ERROR }}  *Skipped:* ${{ steps.parse_counts.outputs.SKIPPED }}  *XFail:* ${{ steps.parse_counts.outputs.XFAIL }}"
+                        "text": "*Passed:* ${{ steps.parse_counts.outputs.PASSED }}   *Failed:* ${{ steps.parse_counts.outputs.FAILED }}   *Error:* ${{ steps.parse_counts.outputs.ERROR }}   *Skipped:* ${{ steps.parse_counts.outputs.SKIPPED }}   *XFail:* ${{ steps.parse_counts.outputs.XFAIL }}"
                       }
                     },
                     {
@@ -297,80 +439,22 @@ jobs:
                         },
                         {
                           "type": "mrkdwn",
-                          "text": "*Status:* ✅ Passed"
+                          "text": "*Status:* ${{ job.status == 'success' && ':white_check_mark:' || ':x:' }}"
                         }
                       ]
                     },
                     {
-                      "type": "image",
-                      "title": {
-                        "type": "plain_text",
-                        "text": "Test Summary Charts"
-                      },
-                      "image_url": "${{ env.COMBINED_URL }}",
-                      "alt_text": "Pie + Bar Chart"
-                    },
-                    {
-                      "type": "section",
-                      "text": {
-                        "type": "mrkdwn",
-                        "text": "Here's the corresponding report :arrow_right::arrow_right:"
-                      },
-                      "accessory": {
-                        "type": "button",
-                        "text": {
-                          "type": "plain_text",
-                          "text": "Click to Download",
-                          "emoji": true
-                        },
-                        "url": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}/artifacts/${{ steps.artifact-upload-step.outputs.artifact-id }}",
-                        "style": "primary",
-                        "action_id": "button-action"
-                      }
-                    }
-                  ]
-                }
-              ]
-            }
-
-        env:
-          SLACK_WEBHOOK_URL: ${{ fromJSON(steps.configure_slack.outputs.result).SLACK_WEBHOOK_URL }}
-          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
-
-      - name: Post to Slack channel on Failure
-        if: ${{ fromJSON(steps.configure_slack.outputs.result).SLACK_WEBHOOK_URL != '' && failure() }}
-        uses: slackapi/slack-github-action@v1.23.0
-        with:
-          payload: |
-            {
-              "attachments": [
-                {
-                  "color": "#FF0000",
-                  "blocks": [
-                    {
-                      "type": "section",
-                      "text": {
-                        "type": "mrkdwn",
-                        "text": "Hey 👋 \n*${{ github.workflow }}* has failed! ❌\n"
-                      }
-                    },
-                    {
-                      "type": "section",
-                      "text": {
-                        "type": "mrkdwn",
-                        "text": "*Passed:* ${{ steps.parse_counts.outputs.PASSED }}  *Failed:* ${{ steps.parse_counts.outputs.FAILED }}  *Error:* ${{ steps.parse_counts.outputs.ERROR }}  *Skipped:* ${{ steps.parse_counts.outputs.SKIPPED }}  *XFail:* ${{ steps.parse_counts.outputs.XFAIL }}"
-                      }
-                    },
-                    {
-                      "type": "context",
+                      "type": "actions",
                       "elements": [
                         {
-                          "type": "mrkdwn",
-                          "text": "*Environment:* ${{ matrix.environment }}"
-                        },
-                        {
-                          "type": "mrkdwn",
-                          "text": "*Status:* ❌ Failed"
+                          "type": "button",
+                          "text": {
+                            "type": "plain_text",
+                            "text": "⬇️ Click to Download Report",
+                            "emoji": true
+                          },
+                          "url": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}/artifacts/${{ steps.artifact-upload-step.outputs.artifact-id }}",
+                          "style": "${{ job.status == 'success' && 'primary' || 'danger' }}"
                         }
                       ]
                     },
@@ -382,24 +466,6 @@ jobs:
                       },
                       "image_url": "${{ env.COMBINED_URL }}",
                       "alt_text": "Pie + Bar Chart"
-                    },
-                    {
-                      "type": "section",
-                      "text": {
-                        "type": "mrkdwn",
-                        "text": "Here's the corresponding report :arrow_right::arrow_right:"
-                      },
-                      "accessory": {
-                        "type": "button",
-                        "text": {
-                          "type": "plain_text",
-                          "text": "Click to Download",
-                          "emoji": true
-                        },
-                        "url": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}/artifacts/${{ steps.artifact-upload-step.outputs.artifact-id }}",
-                        "style": "danger",
-                        "action_id": "button-action"
-                      }
                     }
                   ]
                 }
diff --git a/.github/workflows/request_api.yml b/.github/workflows/request_api.yml
--- a/.github/workflows/request_api.yml
+++ b/.github/workflows/request_api.yml
@@ -181,109 +181,257 @@ jobs:
       run: |
         echo "COMBINED_JSON=$COMBINED_JSON"
         echo "COMBINED_URL=$COMBINED_URL"
+        
 
-    - name: Post to Slack channel on Success
-      id: slack_success
-      uses: slackapi/slack-github-action@v1.23.0
-      if: ${{ fromJSON(steps.configure_slack.outputs.result).SLACK_WEBHOOK_URL != ' ' && success() }}
-      with:
-        payload: |
-          {
-            	"attachments": [
-            		{
-            			"color": "#36a64f",
-            			"blocks": [
-            				{
-            					"type": "section",
-            					"text": {
-            						"type": "mrkdwn",
-            						"text": " Hola  👋 \n*${{ github.workflow }}* were just triggered! \n"
-            					}
-            				},
-            				{
-            					"type": "section",
-            					"text": {
-            						"type": "mrkdwn",
-            						"text": "*Passed:* ${{ steps.parse_counts.outputs.PASSED }} *Failed:* ${{ steps.parse_counts.outputs.FAILED }} *Error:* ${{ steps.parse_counts.outputs.ERROR }} *Skipped:* ${{ steps.parse_counts.outputs.SKIPPED }} *XFail:* ${{ steps.parse_counts.outputs.XFAIL }}\n"
-            					}
-            				},
-            				{
-            					"type": "context",
-            					"elements": [
-            						{
-            							"type": "mrkdwn",
-            							"text": "*Environment: *\n ${{ matrix.environment }}  \n"
-            						},
-            						{
-            							"type": "mrkdwn",
-            							"text": " "
-            						},
-            						{
-            							"type": "mrkdwn",
-            							"text": "*Status: *\n ${{ job.status }}  :white_check_mark:"
-            						}
-            					]
-            				},
-            				{
-            					"type": "section",
-            					"text": {
-            						"type": "mrkdwn",
-            						"text": "Here's the corresponding report :arrow_right::arrow_right:"
-            					},
-            					"accessory": {
-            						"type": "button",
-            						"text": {
-            							"type": "plain_text",
-            							"text": "Click to Downlaod",
-            							"emoji": true
-            						},
-            						"value": "click_me_123",
-            						"url": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}/artifacts/${{ steps.artifact-upload-step.outputs.artifact-id }}",
-            						"action_id": "button-action",
-            						"style": "primary"
-            					}
-            				},
-                            {
-                                "type": "image",
-                                "title": {
-                                  "type": "plain_text",
-                                  "text": "Test Summary Charts"
-                                },
-                                "image_url": "${{ env.COMBINED_URL }}",
-                                "alt_text": "Pie + Bar Chart"
-                            }          
-            			]
-            		}
-            	]
-            }
-        parse-json-secrets: true
-      env:
-        SLACK_WEBHOOK_URL: ${{ fromJSON(steps.configure_slack.outputs.result).SLACK_WEBHOOK_URL }}
-        SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
+#
+#    - name: Post to Slack channel on Success
+#      id: slack_success
+#      uses: slackapi/slack-github-action@v1.23.0
+#      if: ${{ fromJSON(steps.configure_slack.outputs.result).SLACK_WEBHOOK_URL != ' ' && success() }}
+#      with:
+#        payload: |
+#          {
+#            	"attachments": [
+#            		{
+#            			"color": "#36a64f",
+#            			"blocks": [
+#            				{
+#            					"type": "section",
+#            					"text": {
+#            						"type": "mrkdwn",
+#            						"text": " Hola  👋 \n*${{ github.workflow }}* were just triggered! \n"
+#            					}
+#            				},
+#            				{
+#            					"type": "section",
+#            					"text": {
+#            						"type": "mrkdwn",
+#            						"text": "*Passed:* ${{ steps.parse_counts.outputs.PASSED }} *Failed:* ${{ steps.parse_counts.outputs.FAILED }} *Error:* ${{ steps.parse_counts.outputs.ERROR }} *Skipped:* ${{ steps.parse_counts.outputs.SKIPPED }} *XFail:* ${{ steps.parse_counts.outputs.XFAIL }}\n"
+#            					}
+#            				},
+#            				{
+#            					"type": "context",
+#            					"elements": [
+#            						{
+#            							"type": "mrkdwn",
+#            							"text": "*Environment: *\n ${{ matrix.environment }}  \n"
+#            						},
+#            						{
+#            							"type": "mrkdwn",
+#            							"text": " "
+#            						},
+#            						{
+#            							"type": "mrkdwn",
+#            							"text": "*Status: *\n ${{ job.status }}  :white_check_mark:"
+#            						}
+#            					]
+#            				},
+#            				{
+#            					"type": "section",
+#            					"text": {
+#            						"type": "mrkdwn",
+#            						"text": "Here's the corresponding report :arrow_right::arrow_right:"
+#            					},
+#            					"accessory": {
+#            						"type": "button",
+#            						"text": {
+#            							"type": "plain_text",
+#            							"text": "Click to Downlaod",
+#            							"emoji": true
+#            						},
+#            						"value": "click_me_123",
+#            						"url": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}/artifacts/${{ steps.artifact-upload-step.outputs.artifact-id }}",
+#            						"action_id": "button-action",
+#            						"style": "primary"
+#            					}
+#            				},
+#                            {
+#                                "type": "image",
+#                                "title": {
+#                                  "type": "plain_text",
+#                                  "text": "Test Summary Charts"
+#                                },
+#                                "image_url": "${{ env.COMBINED_URL }}",
+#                                "alt_text": "Pie + Bar Chart"
+#                            }
+#            			]
+#            		}
+#            	]
+#            }
+#        parse-json-secrets: true
+#      env:
+#        SLACK_WEBHOOK_URL: ${{ fromJSON(steps.configure_slack.outputs.result).SLACK_WEBHOOK_URL }}
+#        SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
+#
+#    - name: Post to Slack channel on Failure
+#      id: slack_fail
+#      uses: slackapi/slack-github-action@v1.23.0
+#      if: ${{ fromJSON(steps.configure_slack.outputs.result).SLACK_WEBHOOK_URL != ' ' && failure() }}
+#      with:
+#        payload: |
+#          {
+#            "attachments": [
+#              {
+#                "color": "#36a64f",
+#                "blocks": [
+#                  {
+#                    "type": "section",
+#                    "text": {
+#                      "type": "mrkdwn",
+#                      "text": "Hey 👋 \n*${{ github.workflow }}* just finished successfully! 🎉\n"
+#                    }
+#                  },
+#                  {
+#                    "type": "section",
+#                    "text": {
+#                      "type": "mrkdwn",
+#                      "text": "*Passed:* ${{ steps.parse_counts.outputs.PASSED }}  *Failed:* ${{ steps.parse_counts.outputs.FAILED }}  *Error:* ${{ steps.parse_counts.outputs.ERROR }}  *Skipped:* ${{ steps.parse_counts.outputs.SKIPPED }}  *XFail:* ${{ steps.parse_counts.outputs.XFAIL }}"
+#                    }
+#                  },
+#                  {
+#                    "type": "context",
+#                    "elements": [
+#                      {
+#                        "type": "mrkdwn",
+#                        "text": "*Environment:* ${{ matrix.environment }}"
+#                      },
+#                      {
+#                        "type": "mrkdwn",
+#                        "text": "*Status:* ✅ Passed"
+#                      }
+#                    ]
+#                  },
+#                  {
+#                    "type": "image",
+#                    "title": {
+#                      "type": "plain_text",
+#                      "text": "Test Summary Charts"
+#                    },
+#                    "image_url": "${{ env.COMBINED_URL }}",
+#                    "alt_text": "Pie + Bar Chart"
+#                  },
+#                  {
+#                    "type": "section",
+#                    "text": {
+#                      "type": "mrkdwn",
+#                      "text": "Here's the corresponding report :arrow_right::arrow_right:"
+#                    },
+#                    "accessory": {
+#                      "type": "button",
+#                      "text": {
+#                        "type": "plain_text",
+#                        "text": "Click to Download",
+#                        "emoji": true
+#                      },
+#                      "url": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}/artifacts/${{ steps.artifact-upload-step.outputs.artifact-id }}",
+#                      "style": "primary",
+#                      "action_id": "button-action"
+#                    }
+#                  }
+#                ]
+#              }
+#            ]
+#          }
+#        parse-json-secrets: true
+#      env:
+#        SLACK_WEBHOOK_URL: ${{ fromJSON(steps.configure_slack.outputs.result).SLACK_WEBHOOK_URL }}
+#        SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
+#
+#    - name: Post to Slack channel on Failure
+#      if: ${{ fromJSON(steps.configure_slack.outputs.result).SLACK_WEBHOOK_URL != '' && failure() }}
+#      uses: slackapi/slack-github-action@v1.23.0
+#      with:
+#        payload: |
+#          {
+#            "attachments": [
+#              {
+#                "color": "#FF0000",
+#                "blocks": [
+#                  {
+#                    "type": "section",
+#                    "text": {
+#                      "type": "mrkdwn",
+#                      "text": "Hey 👋 \n*${{ github.workflow }}* has failed! ❌\n"
+#                    }
+#                  },
+#                  {
+#                    "type": "section",
+#                    "text": {
+#                      "type": "mrkdwn",
+#                      "text": "*Passed:* ${{ steps.parse_counts.outputs.PASSED }}  *Failed:* ${{ steps.parse_counts.outputs.FAILED }}  *Error:* ${{ steps.parse_counts.outputs.ERROR }}  *Skipped:* ${{ steps.parse_counts.outputs.SKIPPED }}  *XFail:* ${{ steps.parse_counts.outputs.XFAIL }}"
+#                    }
+#                  },
+#                  {
+#                    "type": "context",
+#                    "elements": [
+#                      {
+#                        "type": "mrkdwn",
+#                        "text": "*Environment:* ${{ matrix.environment }}"
+#                      },
+#                      {
+#                        "type": "mrkdwn",
+#                        "text": "*Status:* ❌ Failed"
+#                      }
+#                    ]
+#                  },
+#                  {
+#                    "type": "image",
+#                    "title": {
+#                      "type": "plain_text",
+#                      "text": "Test Summary Charts"
+#                    },
+#                    "image_url": "${{ env.COMBINED_URL }}",
+#                    "alt_text": "Pie + Bar Chart"
+#                  },
+#                  {
+#                    "type": "section",
+#                    "text": {
+#                      "type": "mrkdwn",
+#                      "text": "Here's the corresponding report :arrow_right::arrow_right:"
+#                    },
+#                    "accessory": {
+#                      "type": "button",
+#                      "text": {
+#                        "type": "plain_text",
+#                        "text": "Click to Download",
+#                        "emoji": true
+#                      },
+#                      "url": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}/artifacts/${{ steps.artifact-upload-step.outputs.artifact-id }}",
+#                      "style": "danger",
+#                      "action_id": "button-action"
+#                    }
+#                  }
+#                ]
+#              }
+#            ]
+#          }
+#        parse-json-secrets: true
+#      env:
+#        SLACK_WEBHOOK_URL: ${{ fromJSON(steps.configure_slack.outputs.result).SLACK_WEBHOOK_URL }}
+#        SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
 
-    - name: Post to Slack channel on Failure
-      id: slack_fail
-      uses: slackapi/slack-github-action@v1.23.0
-      if: ${{ fromJSON(steps.configure_slack.outputs.result).SLACK_WEBHOOK_URL != ' ' && failure() }}
+    - name: Post Slack Notification
+      if: ${{ success() || failure() }}
+      uses: slackapi/slack-github-action@v1.25.0
       with:
         payload: |
           {
             "attachments": [
               {
-                "color": "#36a64f",
+                "color": "${{ job.status == 'success' && '#36a64f' || '#FF0000' }}",
                 "blocks": [
                   {
                     "type": "section",
                     "text": {
                       "type": "mrkdwn",
-                      "text": "Hey 👋 \n*${{ github.workflow }}* just finished successfully! 🎉\n"
+                      "text": "Hola 👋 \n*${{ github.workflow }}* just ran!"
                     }
                   },
                   {
                     "type": "section",
                     "text": {
                       "type": "mrkdwn",
-                      "text": "*Passed:* ${{ steps.parse_counts.outputs.PASSED }}  *Failed:* ${{ steps.parse_counts.outputs.FAILED }}  *Error:* ${{ steps.parse_counts.outputs.ERROR }}  *Skipped:* ${{ steps.parse_counts.outputs.SKIPPED }}  *XFail:* ${{ steps.parse_counts.outputs.XFAIL }}"
+                      "text": "*Passed:* ${{ steps.parse_counts.outputs.PASSED }}   *Failed:* ${{ steps.parse_counts.outputs.FAILED }}   *Error:* ${{ steps.parse_counts.outputs.ERROR }}   *Skipped:* ${{ steps.parse_counts.outputs.SKIPPED }}   *XFail:* ${{ steps.parse_counts.outputs.XFAIL }}"
                     }
                   },
                   {
@@ -295,80 +443,22 @@ jobs:
                       },
                       {
                         "type": "mrkdwn",
-                        "text": "*Status:* ✅ Passed"
+                        "text": "*Status:* ${{ job.status == 'success' && ':white_check_mark:' || ':x:' }}"
                       }
                     ]
                   },
                   {
-                    "type": "image",
-                    "title": {
-                      "type": "plain_text",
-                      "text": "Test Summary Charts"
-                    },
-                    "image_url": "${{ env.COMBINED_URL }}",
-                    "alt_text": "Pie + Bar Chart"
-                  },
-                  {
-                    "type": "section",
-                    "text": {
-                      "type": "mrkdwn",
-                      "text": "Here's the corresponding report :arrow_right::arrow_right:"
-                    },
-                    "accessory": {
-                      "type": "button",
-                      "text": {
-                        "type": "plain_text",
-                        "text": "Click to Download",
-                        "emoji": true
-                      },
-                      "url": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}/artifacts/${{ steps.artifact-upload-step.outputs.artifact-id }}",
-                      "style": "primary",
-                      "action_id": "button-action"
-                    }
-                  }
-                ]
-              }
-            ]
-          }
-        parse-json-secrets: true
-      env:
-        SLACK_WEBHOOK_URL: ${{ fromJSON(steps.configure_slack.outputs.result).SLACK_WEBHOOK_URL }}
-        SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
-
-    - name: Post to Slack channel on Failure
-      if: ${{ fromJSON(steps.configure_slack.outputs.result).SLACK_WEBHOOK_URL != '' && failure() }}
-      uses: slackapi/slack-github-action@v1.23.0
-      with:
-        payload: |
-          {
-            "attachments": [
-              {
-                "color": "#FF0000",
-                "blocks": [
-                  {
-                    "type": "section",
-                    "text": {
-                      "type": "mrkdwn",
-                      "text": "Hey 👋 \n*${{ github.workflow }}* has failed! ❌\n"
-                    }
-                  },
-                  {
-                    "type": "section",
-                    "text": {
-                      "type": "mrkdwn",
-                      "text": "*Passed:* ${{ steps.parse_counts.outputs.PASSED }}  *Failed:* ${{ steps.parse_counts.outputs.FAILED }}  *Error:* ${{ steps.parse_counts.outputs.ERROR }}  *Skipped:* ${{ steps.parse_counts.outputs.SKIPPED }}  *XFail:* ${{ steps.parse_counts.outputs.XFAIL }}"
-                    }
-                  },
-                  {
-                    "type": "context",
+                    "type": "actions",
                     "elements": [
                       {
-                        "type": "mrkdwn",
-                        "text": "*Environment:* ${{ matrix.environment }}"
-                      },
-                      {
-                        "type": "mrkdwn",
-                        "text": "*Status:* ❌ Failed"
+                        "type": "button",
+                        "text": {
+                          "type": "plain_text",
+                          "text": "⬇️ Click to Download Report",
+                          "emoji": true
+                        },
+                        "url": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}/artifacts/${{ steps.artifact-upload-step.outputs.artifact-id }}",
+                        "style": "${{ job.status == 'success' && 'primary' || 'danger' }}"
                       }
                     ]
                   },
@@ -380,24 +470,6 @@ jobs:
                     },
                     "image_url": "${{ env.COMBINED_URL }}",
                     "alt_text": "Pie + Bar Chart"
-                  },
-                  {
-                    "type": "section",
-                    "text": {
-                      "type": "mrkdwn",
-                      "text": "Here's the corresponding report :arrow_right::arrow_right:"
-                    },
-                    "accessory": {
-                      "type": "button",
-                      "text": {
-                        "type": "plain_text",
-                        "text": "Click to Download",
-                        "emoji": true
-                      },
-                      "url": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}/artifacts/${{ steps.artifact-upload-step.outputs.artifact-id }}",
-                      "style": "danger",
-                      "action_id": "button-action"
-                    }
                   }
                 ]
               }
