added execution blockers

diff --git a/.github/workflows/multi-select-tests.yml b/.github/workflows/multi-select-tests.yml
--- a/.github/workflows/multi-select-tests.yml
+++ b/.github/workflows/multi-select-tests.yml
@@ -21,7 +21,23 @@ on:
     - cron: '30 7 * * 1-5'
 
 jobs:
+  block_invalid_env:
+    runs-on: ubuntu-latest
+    steps:
+      - id: invalid-deploy
+        if: ${{ github.event_name == 'repository_dispatch' && github.event.client_payload.environment != 'production' }}
+        run: |
+          echo "❌ Deployment runs are not meant for the 'non-production' environment."
+          exit 1
+
+      - id: block-non-approved
+        if: ${{ github.event_name == 'repository_dispatch' && github.event.client_payload.environment == 'india' }}
+        run: |
+          echo "❌ Invalid environment: ${{ github.event.client_payload.environment }}"
+          exit 1
+
   set_matrix:
+    needs: block_invalid_env
     runs-on: ubuntu-latest
     if: ${{ !(github.event_name == 'repository_dispatch' && github.event.client_payload.environment == 'staging') }}
     outputs:
@@ -43,16 +59,6 @@ jobs:
         if: ${{ github.event_name != 'repository_dispatch' }}
         run: |
           echo "::set-output name=matrix::{\"environment\": [\"production\", \"staging\", \"eu\"]}"
-      - id: invalid-deploy
-        if: ${{ github.event_name == 'repository_dispatch' && github.event.client_payload.environment != 'production' }}
-        run: |
-          echo "Invalid environment: ${{ github.event.client_payload.environment }}"
-          exit 1
-      - id: block-india-deploy
-        if: ${{ github.event_name == 'repository_dispatch' && github.event.client_payload.environment == 'india' }}
-        run: |
-          echo "India environment is not allowed for deployment runs."
-          exit 1
 
   build:
     needs: set_matrix
